### PR TITLE
Implement BSON serialization Logic and Tests 

### PR DESCRIPTION
**Pull request by 7uperior**
This commit introduces several key components for BSON serialization:

- Added `SerBson.jl` implementing the BSON deserialization interface.
- Added `test/Ser/SerBson.jl` comprising tests for the serialization logic.
- Updated `test/runtests.jl` to include BSON serialization tests.

These changes address tasks from issue #19, focusing on crafting a BSON serialization interface and developing a robust test suite

### Pull request checklist

- [x] Did you bump the project version?
- [x] Did you add a description to the Pull Request?
- [x] Did you add new tests?
- [x] Did you add reviewers?

### CODE REVIEW

**Comment by dmitrii-doronin** [comment]
Hello again, @7uperior! I am glad to see you're back so soon with a new commit. Let's work sequentially and finish with the first one. I'm sure you'll be able to make some improvements here afterwards and get merged pronto)

**Comment by dmitrii-doronin** [comment]
I am closing this PR due to inactivity.

**Comment by 7uperior** [comment]
NP, I'll re-open or create a new one if necessary

**Comment by NeroBlackstone** [comment]
> NP, I'll re-open or create a new one if necessary

Thank you for providing the preliminary prototype implementation. Are you willing to reopen the PR or would you like others to implement it?

**Pull request closed without merging**
